### ISSUE TITLE
Please Provide Manufacturing part no for below component

### ISSUE THREAD

**Issue by mightChamp** [pavkriz/knxduino#2]
Hello, 

Thanks for this great work, we followed your work, and stuck in some part no of component, It would be great, if you can provide.

Please Provide Manufacturing part no for below component

No  Parts    Component (Package)

1)  DBG     CONN_07LOCK (1X07_LOCK)

2)  T1      NMOSSOT23 (SOT-23 ) 

3)  L3      150mH Inductor(BS11_LIEGEND)

4)  D4      3V3 ZENER-DIODE (SOT23)   

5)  U1      OSCILLATOR5X3 (SMD-5X3)

6)  KNX     WAGO-243-211 (WAGO-243-211)

**Comment by sgiebels** [comment]
Hi, from another KNXduino enthusiast here, waiting for the last parts of my order to arrive.
Not 100% sure about everything, but this is what I've ordered from Mouser so far (parts for 10 KNXduino boards):

KNXDUINO				
Mouser-nr	Mfg.no.	Manufacturer	Description(dutch)   Amount  Price/1
511-STM32G071KBT6 | STM32G071KBT6 | STMicroelectronics | ARM-microcontrollers - MCU 16/32-BITS MICROS | 10 | € 2,78
490-VXO7805-500 | VXO7805-500 | CUI Inc. | Niet-geïsoleerde gelijkstroom-gelijkstroom-omvormers  6.5-36Vin 5Vout 0.5A 2.5W SIP non-Iso | 10 | € 2,10
603-RC2512JK-0768RL | RC2512JK-0768RL | Yageo | Weerstanden met dikke folie - SMD 68 Ohms 1 W 2512 5% | 10 | € 0,205
511-LDL1117S33R | LDL1117S33R | STMicroelectronics | LDO-spanningregelaars POWER MANAGEMENT | 10 | € 0,288
625-SMAJ40CA-E3 | SMAJ40CA-E3/61 | Vishay | ESD-onderdrukkers/TVS-diodes 400W 40V 5% Bi | 10 | € 0,234
647-URS1H101MPD1TD | URS1H101MPD1TD | Nichicon | Aluminium elektrolytische condensatoren - radiaal gelood 100uF 50V 85c 10x9 | 10 | € 0,286
434-03-154J | 11P-154J-50 | Fastron | Vaste smoorspoelen RF CHOKE 150mH 5% | 10 | € 1,44
621-DMN6140L-7 | DMN6140L-7 | Diodes Incorporated | MOSFET 31V to 99V N-Ch FET 60Vds 20Vgs 2.3A | 10 | € 0,236
621-MBR0580S1-7 | MBR0580S1-7 | Diodes Incorporated | Schottky-diodes &amp; gelijkrichters SBR 0.5A 80Vrrm 14A Ifsm 80Vrrm 15pF | 20 | € 0,21
710-885012207098 | 885012207098 | Wurth Elektronik | Meerlaagse keramische condensatoren MLCC - SMD/SMT WCAP-CSGP 0.1uF 0805 10% 50V MLCC | 50 | € 0,065
642-ADTSM31YV | ADTSM31YV | Apem | Drukschakelaars SPST-NO OFF-MOM 0.05A 12VDC | 10 | € 0,263
963-EMK325BJ226MM-P | EMK325BJ226MM-P | Taiyo Yuden | Meerlaagse keramische condensatoren MLCC - SMD/SMT SUGGESTED ALTERNATE 963-EMK212BBJ226MG-T | 10 | € 0,31
963-UMK325BJ106MM-P | UMK325BJ106MM-P | Taiyo Yuden | Meerlaagse keramische condensatoren MLCC - SMD/SMT 1210 50VDC 10uF 20% X5R | 10 | € 0,215


Be aware that for some parts (especially the ARM microcontrollers) there is a extremely long delay in delivery, due to covid.
Be careful you don't get the  STM32G071KBT6 'N'-version, as it has a different pin layout.
One of the capacitors from Taiyo Yuden is 'end of life'

KNX WAGO-243-211 (WAGO-243-211)
is a generic KNX-connector plug, which is plugged onto to solder pins. Find the correct length / diameter size for solder pins from the KNX connector spec) and these to your order, I left them out for now.

The OSCILLATOR is optional, I believe.

The DBG CONN_07LOCK (1X07_LOCK) was unavailable, I plan on soldering the IO directly, without connector, to the KNXduino.

I have left out some SMD capacitors and resistors

2021-05-28_17h03m42s Added:
LED's:
720-LYR976-PS-36 | LY R976-PS-36 | Standaard Led's - SMD Standaard Led's - SMD Yellow, 588nm 280mcd, 20mA
720-LSR976-NR-1 | LS R976-NR-1 | Standaard Led's - SMD Standaard Led's - SMD Super Red, 633nm 180mcd, 20mA
720-LOR976-PS-1 | LO R976-PS-1 | Standaard Led's - SMD Standaard Led's - SMD Orange, 606nm 280mcd, 20mA
720-LGR971-KN-1 | LG R971-KN-1 | Standaard Led's - SMD Standaard Led's - SMD Green, 570nm 26mcd, 20mA

And :
652-SMAJ15CA | SMAJ15CA | ESD-onderdrukkers/TVS-diodes ESD-onderdrukkers/TVS-diodes 15volts 5uA 16.4 Amps Bi-Dir
511-STPS0540Z | STPS0540Z | Schottky-diodes &amp; gelijkrichters Schottky-diodes &amp; gelijkrichters 0.5 Amp 40 Volt
821-TS4148RXG | TS4148 RXG | Diodes - Algemeen gebruik, vermogen, schakelingen Diodes -  Algemeen gebruik, vermogen, schakelingen 1206 
78-BZX84C3V3-E3-08 | BZX84C3V3-E3-08 | Zenerdiodes Zenerdiodes 3.3 Volt 0.35W 5%

Kind regards

**Comment by mightChamp** [comment]
Thanks again for response.

**Comment by Tobias007** [comment]
Hi, did you manage to get it working?
